### ISSUE TITLE
国内用户的未知错误 in<module>

### ISSUE THREAD

**Issue by snowlixue** [YongHaoWu/NeteaseCloudMusicFlac#25]
Traceback (most recent call last):
  File "python3_main.py", line 12, in <module>
    r = requests.get(url,headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36'})
。。。  。。。
   raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for ''http://music.163.com/playlist?id=145258012''

报错如上，我是python3 ，win10系统

**Comment by YongHaoWu** [comment]
@snowlixue 你输入的 url 是否有换行键？
我修复好了，现在重新下载脚本，试试？

**Comment by roceys** [comment]
python2 + win10 也有这个问题。

**Comment by roceys** [comment]
重新下载了python3，还是这个问题。把url的引号去掉就正常了。
可以正常下载，但一个歌单只下载了3首就连接中断了，另外没有flac的就自动跳过不下载了（默认下载320k的也好），而且自动匹配的flac才2.03m一首 ，太坑啊。

**Comment by ZJJane** [comment]
@YongHaoWu 
下载时一首歌下了很久都不动，过了很久显示这个，能帮我看下吗？
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    code.write(f.read())
  File "C:\Python27\lib\socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "C:\Python27\lib\httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
socket.error: [Errno 10054]

**Comment by YongHaoWu** [comment]
@ZJJane 这个问题有点复杂, 我这边没办法排查。。你试试重新运行看看？

**Comment by YongHaoWu** [comment]
@ZJJane   我看到你上个留言了，你试试把卡住的那首歌的上下文输出给我看看？
尤其是这个歌曲的链接。

**Comment by ZJJane** [comment]
Floorfiller
find songid:
293747764
find songlink:
http://zhangmenshiting.qianqian.com/data2/music/8286814548d9b996120e18b5ddad76c9/293747790/2937477641515610861848.flac?xcode=efeebb9584f91b3cc9bf3d409e407d1c
./songs_dir/Floorfiller-BFMHits.flac is downloading now ......

Waiting For Love
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    r = requests.get(url, params=payload)
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sug.music.baidu.com', port=80): Max retries exceeded with url: /info/suggestion?from=0&version=2&word=Waiting+For+Love (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000005BE5E48>: Failed to establish a new connection: [Errno 10060] ',))
PS D:\>

**Comment by YongHaoWu** [comment]
@snowlixue @roceys @ZJJane @NanamiArihara 

建议重新看此项目的说明，下载新程序再试试
