### ISSUE TITLE
估计网易云网页的json获取发生了变化

### ISSUE THREAD

**Issue by guijianchou** [YongHaoWu/NeteaseCloudMusicFlac#41]
Glitter & Gold
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    songid = get_songid(value)
  File "main.py", line 40, in get_songid
    d = json.loads(contents, encoding="utf-8")
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by YongHaoWu** [comment]
@guijianchou 并没有，请下载最新的代码，再试试。

**Comment by YongHaoWu** [comment]
@guijianchou  或者分享一下你的歌单~

**Comment by YongHaoWu** [comment]
最新版应该没有任何问题。
