### ISSUE TITLE
运行过程中报错，似乎是超时问题，请问如何解决？

### ISSUE THREAD

**Issue by carloswear** [YongHaoWu/NeteaseCloudMusicFlac#57]
树莓派上的环境如下：
certifi-2018.8.24 chardet-3.0.4 idna-2.7 requests-2.19.1 urllib3-1.23
报错如下：
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7599ee30>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='music.baidu.com', port=80): Max retries exceeded with url: /data/music/fmlink?songIds=315439071&type=flac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7599ee30>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 138, in main
    d = get_song_info(songid)
  File "main.py", line 87, in get_song_info
    r = requests.get(BAIDU_MUSIC_API, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='music.baidu.com', port=80): Max retries exceeded with url: /data/music/fmlink?songIds=315439071&type=flac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7599ee30>: Failed to establish a new connection: [Errno 110] Connection timed out',))

PC上运行环境如下：
Python 3.7.0
Requirement already satisfied: requests in c:\users\51130\appdata\local\programs\python\python37\lib\site-packages (2.19.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\51130\appdata\local\programs\python\python37\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\51130\appdata\local\programs\python\python37\lib\site-packages (from requests) (2018.8.24)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\users\51130\appdata\local\programs\python\python37\lib\site-packages (from requests) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\51130\appdata\local\programs\python\python37\lib\site-packages (from requests) (2.7)

报错如下：
Traceback (most recent call last):
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 196, in connect
    conn = self._new_conn()
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000024A26A6BBE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='sug.music.baidu.com', port=80): Max retries exceeded with url: /info/suggestion?word=%E6%B1%9F%E4%B8%8A%E6%B8%85%E9%A3%8E%E6%B8%B8&version=2&from=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A26A6BBE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 134, in main
    songid = get_songid(value)
  File "main.py", line 74, in get_songid
    r = requests.get(BAIDU_SUGGESTION_API, params=payload)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\51130\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sug.music.baidu.com', port=80): Max retries exceeded with url: /info/suggestion?word=%E6%B1%9F%E4%B8%8A%E6%B8%85%E9%A3%8E%E6%B8%B8&version=2&from=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A26A6BBE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by carloswear** [comment]
下了几首歌之后就会出现这种问题~

**Comment by YongHaoWu** [comment]
@carloswear 

您好，文档里有一个解决方法哈：

**

> 如运行中遇到错误, 可以运行 pip install --upgrade requests (其中一已知错误是 request 2.7.0 以下的版本在多线程下载时出现错误)

**

**Comment by carloswear** [comment]
> @carloswear
> 
> 您好，文档里有一个解决方法哈：
> 
> **
> 
> > 如运行中遇到错误, 可以运行 pip install --upgrade requests (其中一已知错误是 request 2.7.0 以下的版本在多线程下载时出现错误)
> 
> **

您好，谢谢回复。我更新了requests，没有找到2.7.0版本的requests~官网上面的最新是2.19.1，请问这是怎么回事儿？

https://github.com/requests/requests/releases

**Comment by YongHaoWu** [comment]
@carloswear  呀，抱歉，应该是 typo。 我目前没法找到以前的记录，所以之后修正一下这个文档。

那么目前你的 requests 是最新的了，估计会继续报错？

**Comment by carloswear** [comment]
@YongHaoWu 感谢回复，目前尝试下载歌曲较少的歌单，可以完整的下载下来。现在怀疑：
1，之前的歌单中歌曲太多（超过1000首）；
2，特殊字符的歌曲名

我再测试下~等下反馈给你

**Comment by carloswear** [comment]
测试了几次，尝试了各种歌单~同一个歌单，有时候可以，有时候不可以~我可能碰到鬼了 : (
猜测是网络问题~下次换个宽带试试看，

**Comment by YongHaoWu** [comment]
@carloswear  哦，1000首呀。所在的网络环境，除了树莓派，还有电脑可以测试吗？

这样子：你把有1000首的歌单发我， 我试试。
另外，我再加上失败重试的机制。

**Comment by YongHaoWu** [comment]
@carloswear  LOL 小运营商的锅。
想问问，你用树莓派下载了flac后， 会怎么用呢？

**Comment by carloswear** [comment]
@YongHaoWu 树莓派上我安装了OSMC，这个系统基于Debian，集成了Kodi，绝大多数音视频格式都支持。然后通过手机软件Yaste当遥控器来用~无屏也可以操作。音质的话用HDMI播放音质还不错，不过自带耳机接口音质就很一般了，主要是方便。有适配树莓派外置音频解码板~这个就没试过了。

现在是frp的端口转发，加上aria2的远程下载（bt下载/百度），加上您的音频下载，加上samba的局域网文件共享~

![screenshot_20181015-154431](https://user-images.githubusercontent.com/41362266/46936552-45854f80-d091-11e8-8d34-e654b2fc1635.jpg)
![screenshot_20181015-154235](https://user-images.githubusercontent.com/41362266/46936553-461de600-d091-11e8-8070-9217f033442b.jpg)

**Comment by carloswear** [comment]
我用的安卓机~Kodi自己的遥控软件支持本地投屏之类功能，。然后树莓派安了那个命令行的网易云音乐播放器，用起来还行。

Ps: 刚发现系统上集成了DLNA，这下方便多了。绕了一个大圈，又回来了🤣
-------- Original message --------From: YongHao Hu <notifications@github.com> Date: 15/10/2018  16:24  (GMT+08:00) To: YongHaoWu/NeteaseCloudMusicFlac <NeteaseCloudMusicFlac@noreply.github.com> Cc: carloswear <511303702@qq.com>, Mention <mention@noreply.github.com> Subject: Re: [YongHaoWu/NeteaseCloudMusicFlac] 运行过程中报错，似乎是超时问题，请问如何解决？ (#57) 
@carloswear 明白~ 其实我现在没有依赖自己的脚本，233

我是直接用 AirPlay 投放网易云音乐的歌曲在线播放就好了。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/YongHaoWu/NeteaseCloudMusicFlac","title":"YongHaoWu/NeteaseCloudMusicFlac","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/YongHaoWu/NeteaseCloudMusicFlac"}},"updates":{"snippets":[{"icon":"PERSON","message":"@YongHaoWu in #57: @carloswear 明白~ 其实我现在没有依赖自己的脚本，233\r\n我是直接用 AirPlay 投放网易云音乐的歌曲在线播放就好了。"}],"action":{"name":"View Issue","url":"https://github.com/YongHaoWu/NeteaseCloudMusicFlac/issues/57#issuecomment-429752440"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YongHaoWu/NeteaseCloudMusicFlac/issues/57#issuecomment-429752440",
"url": "https://github.com/YongHaoWu/NeteaseCloudMusicFlac/issues/57#issuecomment-429752440",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [YongHaoWu/NeteaseCloudMusicFlac] 运行过程中报错，似乎是超时问题，请问如何解决？ (#57)",
"sections": [
{
"text": "",
"activityTitle": "**YongHao Hu**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@YongHaoWu",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"YongHaoWu/NeteaseCloudMusicFlac\",\n\"issueId\": 57,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"YongHaoWu/NeteaseCloudMusicFlac\",\n\"issueId\": 57\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/YongHaoWu/NeteaseCloudMusicFlac/issues/57#issuecomment-429752440"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388805576\n}"
}
],
"themeColor": "26292E"
}
]
