### ISSUE TITLE
下载了却没song——dir？

### ISSUE THREAD

**Issue by HenacanPodwell** [YongHaoWu/NeteaseCloudMusicFlac#60]
![image](https://user-images.githubusercontent.com/45177066/48721283-89551100-ec5c-11e8-8604-95da6c7f72b7.png)

**Comment by YongHaoWu** [comment]
@HenacanPodwell 歌单麻烦发一下给我看看。

**Comment by HenacanPodwell** [comment]
https://music.163.com/#/song?id=27853588
https://music.163.com/#/song?id=1293886117
尝试了这几首都不能

**Comment by YongHaoWu** [comment]
@HenacanPodwell 不是用歌曲，是用歌单。就是一首首歌曲收藏起来的歌单。

**Comment by YongHaoWu** [comment]
@HenacanPodwell 像这个：https://music.163.com/#/playlist?id=560821171

**Comment by HenacanPodwell** [comment]
![image](https://user-images.githubusercontent.com/45177066/48758510-3cfce600-ecdb-11e8-875f-7a79e810e4de.png)
还是没有额，我用了你的歌单

**Comment by YongHaoWu** [comment]
@liuce-  你的歌单应该是： https://music.163.com/#/playlist?id=365413384
而不是带上 my 的那个路径——那个是你自己的歌单，而我上面的是对外而言的歌单。

**Comment by YongHaoWu** [comment]
@HenacanPodwell  都报错了，链接失败。你是在外国吗？

**Comment by HenacanPodwell** [comment]
对额，外国的。我在chrome上有用个extension，然后就能够用网易云了

**Comment by YongHaoWu** [comment]
@HenacanPodwell  但是你用我的这个 python 脚本，是不走你 chrome 上的代理的。你可以找找我这个项目过往的 issue，有人通过改系统 dns 可以成功。或者你fan 回来中国

**Comment by HenacanPodwell** [comment]
怎么改系统dns？还是fan回来中国？我试了试改了host，可是那个host好像不能用了。

**Comment by liuce-** [comment]
> @liuce- 你的歌单应该是： https://music.163.com/#/playlist?id=365413384
> 而不是带上 my 的那个路径——那个是你自己的歌单，而我上面的是对外而言的歌单。

感谢回复，我试了下你给的这个链接，可以解析歌曲列表。但是依然没有那个文件夹
![image](https://user-images.githubusercontent.com/9114444/48816037-3e8fd380-ed06-11e8-8756-5dd70c0c8b0c.png)
而且我在国外没有使用VPN也能提示下载成功，就是没有文件夹

**Comment by YongHaoWu** [comment]
@liuce- @HenacanPodwell  都在国外的话，估计都要 fan 回国内才可以了-_-

**Comment by liuce-** [comment]
原来是这样，感谢回复！

**Comment by HenacanPodwell** [comment]
@YongHaoWu 哦哦，fan是什么意思啊？ 谢谢w

**Comment by YongHaoWu** [comment]
@HenacanPodwell  翻。用代理回国内的意思

**Comment by KyreFu** [comment]
如果不用代理是和以上相同的情况。我用了代理，但是出现了错误。
‘Remote end closed connection without response’
```

2018-11-25 21:29:46 main.py:43 [INFO] fetching Netease song list from https://music.163.com/playlist?id=12433802

2018-11-25 21:29:48 main.py:72 [INFO] Incomplete
2018-11-25 21:29:48 main.py:81 [INFO] find songid: 12309123
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/anaconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/anaconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/anaconda3/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9090): Max retries exceeded with url: http://music.taihe.com/data/music/fmlink?songIds=12309123&type=flac (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 138, in main
    d = get_song_info(songid)
  File "main.py", line 87, in get_song_info
    r = requests.get(BAIDU_MUSIC_API, params=payload)
  File "/anaconda3/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 644, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 644, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 222, in resolve_redirects
    **adapter_kwargs
  File "/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=9090): Max retries exceeded with url: http://music.taihe.com/data/music/fmlink?songIds=12309123&type=flac (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

```

**Comment by YongHaoWu** [comment]
@KyreFu 你用的是国内的代理吗？

**Comment by KyreFu** [comment]
我用的是transocks（穿梭），是为了看国内电视剧的用的。

**Comment by Iridescentangle** [comment]
好奇怪啊，提示下载成功却没有song_dir目录....

**Comment by YongHaoWu** [comment]
@Iridescentangle 麻烦 参考 https://github.com/YongHaoWu/NeteaseCloudMusicFlac/issues/61，用现在新的脚本试试看
