### ISSUE TITLE
好像付费歌曲是下载不了的

### ISSUE THREAD

**Issue by b4imetu** [YongHaoWu/NeteaseCloudMusicFlac#72]
把专辑《WHEN WE ALL FALL ASLEEP, WHERE DO WE GO》的个加入歌单结果一首都没下载下来，只下载了2首奇怪的东西
`python main.py https://music.163.com/#/playlist?id=2756048199
2019-04-14 22:48:56 main.py:70 [INFO] 歌单: wow

2019-04-14 22:48:56 main.py:170 [INFO] 歌单中包含的歌曲有: ['!!!!!!!', 'bad guy', 'xanny', 'you should see me in a crown', 'all the good girls go to hell', 'wish you were gay', "when the party's over", '8', 'my strange addiction', 'bury a friend', 'ilomilo', 'listen before i go', 'i love you', 'goodbye']
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 !!!!!!! 对应的ID
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 you should see me in a crown 对应的ID
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 all the good girls go to hell 对应的ID
2019-04-14 22:48:56 main.py:107 [INFO] 歌曲 xanny 对应的ID为: 305013446
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 bury a friend 对应的ID
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 wish you were gay 对应的ID
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 ilomilo 对应的ID
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 my strange addiction 对应的ID
2019-04-14 22:48:56 main.py:107 [INFO] 歌曲 8 对应的ID为: 606463030
2019-04-14 22:48:56 main.py:103 [INFO] 未查找到歌曲 listen before i go 对应的ID
2019-04-14 22:48:56 main.py:107 [INFO] 歌曲 when the party's over 对应的ID为: 7548006
2019-04-14 22:48:56 main.py:107 [INFO] 歌曲 goodbye 对应的ID为: 32996864
2019-04-14 22:48:56 main.py:107 [INFO] 歌曲 i love you 对应的ID为: 1013325
2019-04-14 22:48:56 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:57 main.py:107 [INFO] 歌曲 bad guy 对应的ID为: 16586928
2019-04-14 22:48:57 main.py:179 [INFO] 获取歌曲信息完成，开始下载。
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"songname": "Bad Guys", "artist": "Skip Martin", "link": null, "data": false}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"songname": "When The Party'S Over", "artist": "Bloom 06", "link": null, "data": false}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"songname": "Goodbye\u9752\u6625", "artist": "\u738b\u7ece\u9f99", "link": "http://zhangmenshiting.qianqian.com/data2/music/04a07259732f2ca6cb2cb292813c2c99/599168077/329968642016001034.flac?xcode=5f0d26dec621c9c235dc224202a6daff", "size": 24, "data": true}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"songname": "I Love You \u65e0\u671b", "artist": "\u4e94\u6708\u5929", "link": "http://zhangmenshiting.qianqian.com/data2/music/f264894c538d9e5bcf773a477e66d68b/599505592/1013325248400854.flac?xcode=5f0d26dec621c9c235dc224202a6daff", "size": 29, "data": true}
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"songname": "Xannya Markus", "artist": "Electronic Hard", "link": "http://zhangmenshiting.qianqian.com/data2/music/c5992b0e3105bb2bad5a15892418429e/305013510/305013446223200961.flac?xcode=5f0d26dec621c9c235dc224202a6daff", "size": 39, "data": true}
2019-04-14 22:48:57 main.py:148 [INFO] 下载中: C:\Users\b4ime\songs_dir\wow\Xannya Markus-Electronic Hard.flac
2019-04-14 22:48:57 main.py:132 [INFO] 获取歌曲信息 {"songname": "38\u5ea66\uff08DJ\u7248\uff09", "artist": "8\u5148\u751f", "link": null, "data": false}
2019-04-14 22:48:58 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:59 main.py:132 [INFO] 获取歌曲信息 {"data": false}
2019-04-14 22:48:59 main.py:148 [INFO] 下载中: C:\Users\b4ime\songs_dir\wow\I Love You 无望-五月天.flac
2019-04-14 22:48:59 main.py:148 [INFO] 下载中: C:\Users\b4ime\songs_dir\wow\Goodbye青春-王绎龙.flac
2019-04-14 22:49:09 main.py:155 [INFO] 下载完成: C:\Users\b4ime\songs_dir\wow\Goodbye青春-王绎龙.flac
2019-04-14 22:49:11 main.py:155 [INFO] 下载完成: C:\Users\b4ime\songs_dir\wow\I Love You 无望-五月天.flac
Traceback (most recent call last):
  File "main.py", line 194, in <module>
    main()
  File "main.py", line 183, in main
    executor.map(download, song_infos)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 611, in __exit__
    self.shutdown(wait=True)
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 204, in shutdown
    t.join()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python37\lib\threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "C:\Users\b4ime\AppData\Local\Programs\Python\Python37\lib\threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
2019-04-14 22:49:13 main.py:155 [INFO] 下载完成: C:\Users\b4ime\songs_dir\wow\Xannya Markus-Electronic Hard.flac`

**Comment by moenn** [comment]
网易云歌单的链接只是提供了歌曲的名字，程序根据这些歌名从百度音乐网站上下载资源，所以可能百度音乐上没有这些歌曲吧。
