### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by MCredbear** [YongHaoWu/NeteaseCloudMusicFlac#73]
平台是arm64，下面是我的log
firefly@firefly:~/NeteaseCloudMusicFlac$ python3 main.py 'https://music.163.com/#/my/m/music/playlist?id=2749721625'
2019-04-21 12:03:03 main.py:70 [INFO] 歌单: 待下载

2019-04-21 12:03:03 main.py:170 [INFO] 歌单中包含的歌曲有: ['Mermaid girl (Extended RRver.)', '朧', 'Samsara（《剑与轮回》手游主题曲）']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f92e06a20>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='sug.music.baidu.com', port=80): Max retries exceeded with url: /info/suggestion?word=Mermaid+girl+%28Extended+RRver.%29&version=2&from=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92e06a20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 194, in <module>
    main()
  File "main.py", line 178, in main
    song_infos = executor.map(get_song_info, song_ids)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 575, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 575, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 96, in get_songid
    r = requests.get(BAIDU_SUGGESTION_API, params=payload, headers=HEADERS)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sug.music.baidu.com', port=80): Max retries exceeded with url: /info/suggestion?word=Mermaid+girl+%28Extended+RRver.%29&version=2&from=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92e06a20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
firefly@firefly:~/NeteaseCloudMusicFlac$
请问这个该怎么办？

**Comment by moenn** [comment]
好像是因为查询歌曲id 的 url 无法连接了，已经更换了新的查询 url #75 ，
 `git pull`  更新仓库代码后再试一下吧。

**Comment by MCredbear** [comment]
> 好像是因为查询歌曲id 的 url 无法连接了，已经更换了新的查询 url #75 ，
> `git pull` 更新仓库代码后再试一下吧。

可以了，不过这个真的是用网易云的歌库吗？为什么我下下来的和歌单里的不一样？

**Comment by moenn** [comment]
使用的是网易云歌单中的所有歌曲名字，然后去百度音乐下载的，很多歌曲没有对应的资源，而且目前没有将歌手名字加入搜索，所以匹配率低 😿 。 #62 

@YongHaoWu  ，要不要把 **匹配率较低，改进中** 写到 readme 里。

**Comment by YongHaoWu** [comment]
@moenn  没问题啊。其实在readme 有相关的：
TODO list
目前只是匹配歌曲名字，最好加上匹配歌手名
歌曲匹配率不高，可以考虑再到其他网站抓

**Comment by moenn** [comment]
@YongHaoWu 我觉得可以写在 readme 的头部，让使用的人对 *能下载多少歌单里的歌曲，其中有多少是我想要的那首* 有大致预期 😄  。

嗯，可以把歌手名添加到搜索条件里，这几天写一下。

**Comment by MCredbear** [comment]
> @moenn 没问题啊。其实在readme 有相关的：
> TODO list
> 目前只是匹配歌曲名字，最好加上匹配歌手名
> 歌曲匹配率不高，可以考虑再到其他网站抓

ummm，可是我一个生活在二刺螈里的壬好多歌只有网易云有诶。。。不能弄到网易云的API吗？

**Comment by moenn** [comment]
@MCredbear 网易云的话你可以看下这个仓库: `https://github.com/0xHJK/music-dl`，支持从网易云音乐源搜索，但目前只能搜索单曲下载，下载整个歌单的功能还在开发中。
