### ISSUE TITLE
ptyhon小白，下载报错不知如何解决！！！！！

### ISSUE THREAD

**Issue by say1921** [YongHaoWu/NeteaseCloudMusicFlac#88]
执行代码时在windows环境报错：raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

=============================================================

2020-04-11 12:30:21 main.py:106 [INFO] 未查找到歌曲 就值得了爱 对应的ID
2020-04-11 12:30:22 main.py:106 [INFO] 未查找到歌曲 去看星星好不好 对应的ID
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 189, in main
    res = [i for i in song_infos if i['data'] == True]
  File "main.py", line 189, in <listcomp>
    res = [i for i in song_infos if i['data'] == True]
  File "C:\Users\dream\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "C:\Users\dream\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\dream\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\dream\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 117, in get_song_info
    contents = json.loads(r.text,strict=False)
  File "C:\Users\dream\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "C:\Users\dream\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\dream\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by CharlesPikachu** [comment]
可以试试这个项目：https://github.com/CharlesPikachu/Music-Downloader

**Comment by STrelitziAaaa** [comment]
main.py  get_song_info函数 113行
修改contents = json.loads(r.text)为
```py 
    song_info = {}
    contents = {}
    try:
        contents = json.loads(r.text)
    except:
        contents['errorCode'] = 0
```
错误原因可能是requests请求超时导致返回了空的response,无法被json解析
